backend:
  name: github
  repo: HonzaDudek/alzaTechFridayDemo
  branch: main
  base_url: https://cmsazuredemofunc.azurewebsites.net,
media_folder: public/img
public_folder: public
collections:
  - label: "Novinky"
    name: "news"
    create: true
    folder: "pages/news"
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Author", name: "author", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown"}

